api/urls.py
from django.urls import include, path, re_path
from .views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)




urlpatterns = [
    path('token/',MyTokenObtainPairView.as_view(),name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(),name='token_refresh'),
    path('konfirmasi', KonfirmasiAPI.as_view(), name = 'konfirmasi'),
    # re_path(r'^artikel/(?P<pk>\d+)/$', ArticleList.as_view(),name = 'artikel'),
    path('registrasi/mahasiswa',MahasiswaAPI.as_view(), name = 'registrasi-mahasiswa'),
    path('registrasi/psikolog',PsikologAPI.as_view(), name = 'registrasi-psikolog'),
    path('artikel',ArticleAPI.as_view(),name = 'artikel-get'),
    path('artikel/<int:pk>',ArticleAPI.as_view(),name = 'artikel-other'),
    path('saran',SuggestionAPI.as_view(),name = 'saran'),
    path('konsultasi',ConsultationAPI.as_view(), name = 'konsultasi'),
    path('donasi',DonasiAPI.as_view(), name = 'donasi')
]

home/home/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

konfirmasi/urls.py
from django.urls import path
from django.contrib import admin

from article.views import delete_post
from .views import index, accept, reject, delete_post

urlpatterns = [
    path('', index, name='index'),
    path('accept', accept, name='accept'),
    path('reject', reject, name='reject'),
    path('delete_post', delete_post, name='delete_post'),
]

tkpbp/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from article.views import index as index_konfirmasi
import article.urls as article
import accounts.urls as accounts
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('konfirmasi/', include(('konfirmasi.urls','konfirmasi'),namespace='konfirmasi')),
    path('',include(accounts)),
    path('artikel/', include(('article.urls','article'), namespace='article')),
    # re_path(r'^$', index_konfirmasi, name='index'),
    path('consultation/', include(('consultation_form.urls', 'consultation_form'), namespace='consultation_form')),
    # re_path(r'^$', index_article, name='index'),
    path('donasi/', include(('donation.urls', 'donation'), namespace='donasi')),
    path('threader/', include(('threader.urls', 'threader'), namespace='diskusi')),
    path('quiz/', include('quiz.urls')),
    path('api/',include('api.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

konfirmasi/models.py
from django.db import models
from consultation_form.models import Consultation

# Create your models here.
class Konsultasi(models.Model):
    full_name = models.CharField(max_length=150)
    npm = models.CharField(max_length=50)
    date = models.DateField()
    email = models.CharField(max_length=50)

konfirmasi/views.py
from django.shortcuts import render
from consultation_form.models import Consultation
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse


@login_required
def index(request):
    konsuls = Consultation.objects.all().values()
    response = {'konsuls' : konsuls,'nbar' : 'Konfirmasi'}
    return render(request, 'konfirmasi_konsultasi.html', response)

def stringpurifier(words):
    newStr = ""
    for i in words:
        if i != " " or i != "\n":
            newStr += i
    return(" ".join(newStr.split()))    

@csrf_exempt
def delete_post(request):
    full_name = stringpurifier(request.POST.get("full_name")) 
    try:
        Consultation.objects.get(full_name=full_name).delete()
        konsultasi_data={"error":False,"errorMessage":"Deleted Successfully", "full_name":full_name}
        return JsonResponse(konsultasi_data,safe=False)
    except:
        konsultasi_data={"error":True,"errorMessage":"Failed to Delete Data", "full_name":full_name}
        return JsonResponse(konsultasi_data,safe=False)

def accept(request):
    return render(request, 'accept.html')

def reject(request):
    return render(request, 'reject.html')

konfirmasi/templates/accept.html
{% extends 'base.html' %}
{% load static %}
    {% block css %}
    {{block.super}}
    <link rel="stylesheet" href="{% static '../static/token.css' %}">
    {% endblock %}
    {% block body %}
        {{block.super}}
        <p>Selamat, Anda menerima konsultasi !!</p>
    {% endblock %}    

konfirmasi/templates/konfirmasi_konsultasi.html
{% extends 'base.html' %}
{% load static %}
    {% block css %}
    {{block.super}}
    <link rel="stylesheet" href="{% static '../static/konfirmasi_konsultasi.css' %}">
    <!-- Inter font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter">
    {% endblock %}
    {% block body %}
        {{block.super}}
        <div class="container">
            <div class="heading">
                <h1>Konfirmasi Konsultasi</h1>
            </div>
            <div class="row">
                {% for konsul in konsuls %}
                <div class="card">
                    <div class="card-body">
                        <p>Nama     : {{ konsul.full_name }}</p>
                        <p>NPM      : {{ konsul.npm }}</p>
                        <p>Waktu    : {{ konsul.date }}</p>
                        <p>Email    : {{ konsul.email }}</p>
                        <div class="btn d-flex justify-content-center">
                            <a href="{% url 'konfirmasi:accept' %}" class="btn1 text-center">Accept</a>
                            <a href="{% url 'konfirmasi:reject' %}" class="btn2 text-center">Reject</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>       
    {% endblock %}

konfirmasi/templates/reject.html
{% extends 'base.html' %}
{% load static %}
    {% block css %}
    {{block.super}}
    {% endblock %}
    {% block body %}
        {{block.super}}
        <link rel="stylesheet" href="{% static '../static/token.css' %}">
        <p>Sayang sekali, anda menolak konsultasi :(</p>
    {% endblock %}   