api/urls.py
from django.urls import include, path, re_path
from .views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)




urlpatterns = [
    path('token/',MyTokenObtainPairView.as_view(),name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(),name='token_refresh'),
    path('konfirmasi', KonfirmasiAPI.as_view(), name = 'konfirmasi'),
    # re_path(r'^artikel/(?P<pk>\d+)/$', ArticleList.as_view(),name = 'artikel'),
    path('registrasi/mahasiswa',MahasiswaAPI.as_view(), name = 'registrasi-mahasiswa'),
    path('registrasi/psikolog',PsikologAPI.as_view(), name = 'registrasi-psikolog'),
    path('artikel',ArticleAPI.as_view(),name = 'artikel-get'),
    path('artikel/<int:pk>',ArticleAPI.as_view(),name = 'artikel-other'),
    path('saran',SuggestionAPI.as_view(),name = 'saran'),
    path('konsultasi',ConsultationAPI.as_view(), name = 'konsultasi'),
    path('donasi',DonasiAPI.as_view(), name = 'donasi')
]

consultation_form/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('json/<str:city>', views.get_counselor, name='get_counselor'),
    path('submit/<int:pk_counselor>', views.submit_form, name='submit_form')
]

home/home/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tkpbp/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from article.views import index as index_konfirmasi
import article.urls as article
import accounts.urls as accounts
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('konfirmasi/', include(('konfirmasi.urls','konfirmasi'),namespace='konfirmasi')),
    path('',include(accounts)),
    path('artikel/', include(('article.urls','article'), namespace='article')),
    # re_path(r'^$', index_konfirmasi, name='index'),
    path('consultation/', include(('consultation_form.urls', 'consultation_form'), namespace='consultation_form')),
    # re_path(r'^$', index_article, name='index'),
    path('donasi/', include(('donation.urls', 'donation'), namespace='donasi')),
    path('threader/', include(('threader.urls', 'threader'), namespace='diskusi')),
    path('quiz/', include('quiz.urls')),
    path('api/',include('api.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consultation_form/models.py
from django.db import models
from accounts.models import Account

# Create your models here.
class Consultation(models.Model):
    full_name = models.CharField(max_length=50)
    npm = models.PositiveBigIntegerField()
    date = models.DateField()
    email= models.CharField(max_length=50)

    selected_counselor = models.ForeignKey(Account, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.full_name

consultation_form/forms.py
from django.db.models import fields
from django.forms import ModelForm
from django.forms.widgets import DateInput, TextInput
from consultation_form.models import Consultation
from datetime import date

class ConsForm(ModelForm):
    class Meta:
        model = Consultation
        fields = ('full_name', 'npm', 'date', 'email')
        widgets = {'full_name': TextInput(attrs={'class': 'form-control border-dark mb-5'}),
                   'npm': TextInput(attrs={'class': 'form-control border-dark mb-5'}),
                   'date': DateInput(attrs={'class': 'form-control border-dark mb-5', 'type': 'date', 'min': date.today().strftime("%Y-%m-") + "{:0>2}".format(str((int(date.today().strftime("%d")) + 1)))}),
                   'email': TextInput(attrs={'class': 'form-control border-dark mb-5'})}

consultation_form/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
from django.core import serializers
from accounts.models import Account
from consultation_form.forms import ConsForm
from accounts.models import BioPsikolog
import json

@login_required(login_url="/login", redirect_field_name=None)
def index(request):
    if (request.user.is_counselor):
        return render(request, "consultation_form_notcounselor.html")
    consultation_form = ConsForm()
    city_list = ['Jakarta',
                 'Bogor',
                 'Depok',
                 'Tangerang',
                 'Bekasi']
    psikolog_list = BioPsikolog.objects.all()
    response = {'consultation_form': consultation_form,
                'city_list': city_list,
                'psikolog_list' : psikolog_list,
                'nbar': 'Konsultasi'
                }
    return render(request, "consultation_form_index.html", response)

def get_counselor(request, city=None):
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    if (is_ajax and request.method == 'GET'):
        counselor = Account.objects.filter(is_counselor=True,biopsikolog__domisili=city)
        counselor_bio = BioPsikolog.objects.filter(user__is_counselor=True,domisili=city)
        print(counselor)
        print(counselor_bio)
        counselor_object = [*counselor,*counselor_bio]
        # If there is no counselor (List is empty)
        if not counselor_object:
            # Return error 404 not found
            return JsonResponse({}, status=404)
        print(type(counselor_object))
        data = serializers.serialize('json', counselor_object)
        print(data)
        print(type(data))
        data_sebar = {'akun_psikolog':data}
        print(data_sebar)
        return HttpResponse(data, content_type='application/json')
    else:
        return JsonResponse({}, status=404)

def submit_form(request, pk_counselor):
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    if (is_ajax and request.method == 'POST'):
        print("trying to submit form")
        counselorInstance = Account.objects.get(pk=pk_counselor)
        # Get the form data and create object ConsForm
        form = ConsForm(request.POST)
        if form.is_valid():
            # Create instance but dont save it yet
            save_form = form.save(commit=False)
            # Assign counselor to form
            save_form.selected_counselor = counselorInstance
            # Save the form
            save_form.save()
            # Return response success
            return JsonResponse({}, status=200)
        else :
            # If form is not valid then return response submit error
            return JsonResponse({}, status=400)

    # if not ajax or request is not post then return error
    return JsonResponse({}, status=400)

consultation_form/templates/consultation_form_base.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block head %}
    {{block.super}}
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Inter font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter">
    <!-- Load static -->
    <link rel="stylesheet" href="{% static 'css/consultation_form_index.css' %}">
    {% block more-import %}{% endblock %}

    <title>{% block title %}Title{% endblock %}</title>
  {% endblock %}
  {% block body %}
    {{block.super}}
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
  {% endblock %}
</html>

consultation_form/templates/consultation_form_index.html
{% extends 'consultation_form_base.html' %}
{% load static %}
{% block title %}Formulir Konsultasi{% endblock %}
{% block more-import %}
<!-- JQuery Import -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/consultation_form.js' %}"></script>
{% endblock %}
{% block body %}
{{block.super}}
<!-- get counselor link -->
<script type="text/javascript">
  var get_counselor_url = "{% url 'consultation_form:get_counselor' 12345 %}".replace(/12345/, '');
  var get_counselor_image = "{% static 'images/user-profile-svgrepo-com.svg' %}";
  var get_sad_image = "{% static 'images/sad-svgrepo-com.svg' %}";
  var formSubmitURL = "{% url 'consultation_form:submit_form' 12345 %}".replace(/12345/, '');
</script>

<div class="container mt-3">
  <h1 class="text-center">Buat jadwal konsultasimu dengan</h1>
  <h1 class="text-center mb-5">RuangSinggah<span class="tk-color-yellow">.</span></h1>
  <div class="row gx-5">
    <div class="col col-xl-4 me-xl-5">
      <form method="POST" action="" id="consultation_form">
        {% csrf_token %}
        <h5>Nama Lengkap</h5>
        {{ consultation_form.full_name }}
        <h5>NPM</h5>
        {{ consultation_form.npm }}
        <h5>Waktu Konsultasi</h5>
        {{ consultation_form.date }}
        <h5>Email</h5>
        {{ consultation_form.email }}
      </form>
    </div>

    <!-- Force next columns to break to new line at xl breakpoint and down -->
  <div class="w-100 d-block d-xl-none"></div>

    <div class="col ms-xl-5">
      <h5>Cari Jadwal Psikolog</h5>
      <svg class="me-2" width="35px" height="36px">
        <use href="{% static 'images/map-svgrepo-com.svg' %}#Capa_1"></use>
      </svg>
      <select id="city-select">
        {% for city in city_list %}
        <option value="{{ city }}">{{ city }}</option>
        {% endfor %}
      </select>
      <div id="counselor-list" class="card-columns mt-3">
        {% for psikolog in psikolog_list %}
          {{psikolog.user.biopsikolog.bio}}
          <div class="card">
            <div class="row">
              <div class="col-2 m-2">
                <img src="{% static 'images/profpic.png' %}" alt="Profile picture" class="card-img-left">
              </div>
              <div class="col m-2">
                <div class="card-body">
                  <h5 class="card-title"> {{psikolog.user}} </h5>
                  <p class="card-text">{{psikolog.bio}} </p>
                </div>
              </div>
            </div>
          </div>
          <br>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<!-- Success Modal -->
<div class="modal fade" id="success-modal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="successModalLabel">Buat jadwal berhasil</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <svg height="200px" width="450px">
          <use height="200px" width="480px" href="{% static 'images/checkmark-done-svgrepo-com.svg' %}#checkmark-done"></use>
        </svg>
        <p id="success-message"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

<!-- Failed Modal -->
<div class="modal fade" id="failed-modal" tabindex="-1" aria-labelledby="failedModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="failedModalLabel">Buat jadwal gagal</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p>Membuat jadwal gagal, Mohon coba lagi.<br>Jika beberapa saat kemudian masih gagal, mohon hubungi kami di kontak yang tersedia</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

consultation_form/templates/consultation_form_notcounselor.html
{% extends 'consultation_form_base.html' %}
{% block body %}
{{block.super}}
<h1>A counselor simply does not submit a counseling form<br>-Sun Tzu, The Art of War</h1>
<p>Ps. Halaman ini mungkin bisa digunakan untuk form acceptance kalo yang login counselor atau bisa redirect jika yg akses counselor?</p>
{% endblock %}

consultation_form/templates/footbar.html
<!-- Grabbed from base.html -->

<footer class="myfooter">
  <div class="row" style="width: 100%;">
    <p class="text-center footerlogo">Ruang Singgah<span class="yellow">.</span></p>
    <p class="text-center footerdesc">Ruang untuk bercerita</p>
    <p class="text-center estimated">Est.2021 Kelompok D04</p>
  </div>
</footer>

consultation_form/templates/location-map-svgrepo-com.svg.html
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="location-map-svgrepo-com" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" width="150">
<circle style="fill:#006775;" cx="256" cy="255.977" r="255.977"/>
<path style="fill:#055661;" d="M506.211,310.479C481.241,425.705,378.75,512,256.052,512c-17.299,0-34.197-1.705-50.543-5.014
	L91.086,392.562l74.812-29.884l102.54-26.825l58.766-204.38L506.211,310.479z"/>
<path style="fill:#FEFEFE;" d="M146.693,305.215c-3.911,1.655-8.724,7.822-12.034,13.137l-42.269,67.44
	c-3.309,5.265-1.755,8.774,2.106,7.12l71.352-30.236c1.304,1.805,55.758,46.532,57.613,45.83l94.969-34.548
	c2.005,0.501,87.749,30.085,92.963,31.639c6.569,2.005,10.229-0.803,10.128-7.822l-1.003-69.447
	c-0.1-7.02,1.003-13.388-5.415-15.695c-9.627-3.46-64.834-26.725-67.19-25.873c-14.441,5.164-79.626,28.631-79.626,28.631
	c-10.179-7.572-54.003-36.855-55.858-38.208c-0.702-0.501-3.009-0.301-6.318,0.802c-7.472,2.508-51.797,23.968-59.369,27.227h-0.05
	V305.215z"/>
<g>
	<path style="fill:#D9DADA;" d="M318.479,374.009c3.259,0.953,87.749,30.085,92.863,31.639l0.301,0.1l0.301,0.1l0.301,0.05
		l0.301,0.05l0.301,0.05l0.301,0.05l0,0l0.301,0.05l0,0l0.251,0.05l0.251,0.05l0.251,0.05h0.251l0,0h0.251h0.251l0,0h0.251h0.251
		h0.251h0.251l0.251-0.05l0.251-0.05l0,0l0.2-0.05l0.2-0.05l0,0l0.2-0.05l0,0l0.2-0.05l0.2-0.05l0,0l0.2-0.05l0,0l0.2-0.1l0.2-0.1
		l0.2-0.1l0,0l0.2-0.1l0.15-0.1l0,0l0.15-0.1l0.15-0.1l0.15-0.15l0.15-0.15l0.15-0.15l0.15-0.15l0.15-0.15l0,0l0.15-0.15l0.15-0.15
		l0.15-0.15l0,0l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.2l0.1-0.251l0.05-0.251l0.05-0.251l0.05-0.251
		l0.05-0.251l0.05-0.251l0,0l0.05-0.251l0,0l0.05-0.251l0.05-0.301l0.05-0.301l0.05-0.301l0,0v-0.301v-0.301v-0.301v-0.301v-0.301
		l-1.003-69.447c-0.1-7.02,1.003-13.388-5.415-15.695c-9.627-3.46-64.834-26.725-67.19-25.873l-29.383,87.247L318.479,374.009z"/>
	<path style="fill:#D9DADA;" d="M165.848,362.677c1.304,1.755,53.451,44.676,57.412,45.83h0.2l44.827-93.113
		c-10.179-7.572-54.003-36.855-55.858-38.208l-46.532,85.442L165.848,362.677z"/>
</g>
<path style="fill:#00CC96;" d="M268.388,335.851h3.059c0.953-4.061,5.164-11.382,7.12-15.193l23.015-47.033
	c10.529-21.01,20.358-41.769,30.787-62.577c11.984-24.018,14.14-47.534-0.05-72.004c-11.182-19.355-34.548-35.551-57.814-35.551
	c-17.349,0-29.333,1.655-43.674,11.132c-9.677,6.418-16.647,13.438-22.915,23.768c-14.692,24.369-12.686,48.087-0.401,72.656
	C209.32,214.608,267.284,331.038,268.388,335.851z"/>
<path style="fill:#07B587;" d="M269.19,335.851h2.256c0.953-4.061,5.164-11.382,7.12-15.193l23.015-47.033
	c10.529-21.01,20.358-41.769,30.787-62.577c11.984-24.018,14.14-47.534-0.05-72.004c-11.182-19.355-34.548-35.551-57.814-35.551
	c-1.805,0-3.61,0-5.315,0.05C269.19,192.696,269.19,182.617,269.19,335.851z"/>
<circle style="fill:#E1E5E6;" cx="269.889" cy="171.235" r="43.227"/>
<path style="fill:#CCCCCC;" d="M269.19,128.063v86.395h0.702c23.868,0,43.223-19.355,43.223-43.223s-19.355-43.223-43.223-43.223
	h-0.702V128.063z"/>
<path style="fill:#E84F4F;" d="M269.892,155.491c8.674,0,15.745,7.02,15.745,15.745c0,8.674-7.02,15.745-15.745,15.745
	c-8.674,0-15.745-7.02-15.745-15.745C254.147,162.56,261.167,155.491,269.892,155.491z"/>
<path style="fill:#C94545;" d="M269.19,155.541v31.439h0.702c8.674,0,15.745-7.02,15.745-15.745c0-8.674-7.02-15.745-15.745-15.745
	h-0.702V155.541z"/>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

consultation_form/templates/navbar.html
<!-- Grabbed from base.html -->

<!-- Imported Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet">



<!-- Style -->
<style>
.yellow{
    color: #FFC948;
}
.mynav{
    background-color: #195BDB;
    font-family: Roboto;
    font-size: 20px;
    font-style: normal;
    font-weight: 500;
    line-height: 35px;
    letter-spacing: -0.017em;
    text-align: left;
    color: white;


}
.mynav .nav-link, .nav-brand{
    color:white;
    margin-top: 14px;
    margin-bottom: 10px;

}
.mynav .logo{
    font-family: Inter;
    font-size: 44px;
    font-style: normal;
    font-weight: 700;
    line-height: 53px;
    letter-spacing: -0.017em;
    text-align: left;
    margin-left: 34px;
    margin-top: 5px;
    margin-bottom: 5px;
}
.mynav .active{
    background-color: #FFC948;
    border-radius: 20px;
    color:black;
    padding-left: 5px;
}

.nav-item{
    margin-left: 10px;
}
.rightnav{
    margin-right: 10px;
}

.myfooter{
    background-color: #195BDB;
    /* position: fixed;
    width:100%;
    height: 60px; */
}
.footerlogo{
    font-family: Inter;
    font-size: 44px;
    font-style: normal;
    font-weight: 700;
    line-height: 53px;
    letter-spacing: -0.017em;
    text-align: left;
    color: white;
    margin-top: 56px;
}
.footerdesc{
    color: #F8CF2D;
    font-family: Inter;
    font-size: 24px;
    font-style: normal;
    font-weight: 700;
    line-height: 29px;
    letter-spacing: -0.017em;
    text-align: center;


}
.estimated{
    margin-top: 78px;
    font-family: Roboto;
    font-size: 24px;
    font-style: normal;
    font-weight: 500;
    line-height: 28px;
    letter-spacing: -0.017em;
    text-align: left;

}

/* .custom-toggler .navbar-toggler-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255,102,203, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");
} */
.navbar-dark .navbar-nav .nav-link {
    color: white;
}
.navbar-dark .navbar-nav .nav-link.active{
    color: black;
}
</style>

<nav class="navbar-nav navbar-dark navbar-expand-lg  mynav">
  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbar1">
      <ul class="navbar-nav me-auto ">
          <span class="navbar-brand mb-0 h1 logo">Ruang Singgah<span class="yellow">.</span></span>
          <li class="nav-item">
              <a href="#" class="nav-link {% if nbar == 'Konsultasi' %} active disabled {% endif %}">Konsultasi</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'article:index' %}" class="nav-link {% if nbar == 'Artikel' %} active disabled {% endif %}">Artikel</a>
          </li>
          <li class="nav-item">
              <a href="#" class="nav-link {% if nbar == 'Quiz' %} active disabled {% endif %}">Quiz</a>
          </li>
          <li class="nav-item">
              <a href="#" class="nav-link {% if nbar == 'Diskusi' %} active disabled {% endif %}">Diskusi</a>
          </li>
          <li class="nav-item">
              <a href="#" class="nav-link {% if nbar == 'Donasi' %} active disabled {% endif %}">Donasi</a>
          </li>


      </ul>
      <ul class="navbar-nav rightnav">
          <li class="nav-item">
              <a href="{% url 'registrasi' %}" class="nav-link{% if nbar == 'Registrasi' %} active {% endif %}">Registrasi</a>
          </li>
          <li class="nav-item">
              {% if request.user.is_authenticated %}
              <a href="#" class="nav-link">Halo, {{request.user.name}}!</a>
              {% else %}
                 <a href="{% url 'login' %}" class="nav-link{% if nbar == 'login' %} active {% endif %}   ">Login</a>
              {% endif %}
          </li>
      </ul>
  </div>
</nav>